import { NextRequest, NextResponse } from "next/server";
import { neon } from "@neondatabase/serverless";
import { DRAFT_BATCH, findBlockedClaims } from "@/lib/social/scheduler";

function authorized(req: NextRequest) {
  const secret = process.env.ADMIN_SECRET;
  if (!secret) return false;
  return req.headers.get("authorization") === `Bearer ${secret}`;
}

function db() {
  const url = process.env.DATABASE_URL || process.env.POSTGRES_URL;
  if (!url) return null;
  return neon(url);
}

export async function POST(req: NextRequest) {
  if (!authorized(req)) return NextResponse.json({ ok: false, message: "Unauthorized" }, { status: 401 });

  const sql = db();
  if (!sql) return NextResponse.json({ ok: false, message: "Database env missing" }, { status: 503 });

  let requestedCount = DRAFT_BATCH.length;
  try {
    const body = await req.json();
    if (Number.isFinite(Number(body?.count))) requestedCount = Math.max(1, Math.min(30, Number(body.count)));
  } catch {
    requestedCount = DRAFT_BATCH.length;
  }

  const selected = Array.from({ length: requestedCount }, (_, index) => DRAFT_BATCH[index % DRAFT_BATCH.length]);
  const created = [];
  const blocked = [];

  for (const [index, draft] of selected.entries()) {
    const body = `${draft.hook} ${draft.caption} ${draft.script} ${draft.cta}`;
    const found = findBlockedClaims(body);
    if (found.length) {
      blocked.push({ index, found, hook: draft.hook });
      continue;
    }

    const inserted = await sql`
      insert into bna_content_queue (
        platform,
        language,
        content_type,
        hook,
        caption,
        script,
        cta,
        compliance_status,
        approval_status,
        utm_source,
        utm_campaign,
        notes
      ) values (
        ${draft.platform},
        ${draft.language},
        'short_video',
        ${draft.hook},
        ${draft.caption},
        ${draft.script},
        ${draft.cta},
        'pending_scan',
        'draft',
        'organic_social',
        'tap_the_green_bag_bronx_launch',
        'Generated by draft-only batch generator. Requires proof-loop scan and human approval before export.'
      )
      returning id, platform, language, approval_status, compliance_status, hook
    `;
    created.push(inserted[0]);
  }

  await sql`
    insert into bna_proof_log (loop_name, status, message, evidence)
    values ('social-generate-batch', 'success', 'Draft-only social batch generated; no approval/export/posting performed', ${JSON.stringify({ created: created.length, blocked: blocked.length, autoPublishAllowed: false })}::jsonb)
  `;

  return NextResponse.json({
    ok: true,
    mode: "draft_generation_only",
    autoPublishAllowed: false,
    approvalStatus: "draft",
    complianceStatus: "pending_scan",
    livePostingPerformed: false,
    created: created.length,
    blocked,
    items: created,
    nextRequiredStep: "Run proof-loop scan, then human approval, then scheduler export."
  }, { status: 201 });
}
